SOURCES += $(INCLUDES_DIR)/stack/stack.cpp

include $(INCLUDES_DIR)/stack/dump/Makefile
include $(INCLUDES_DIR)/stack/error/Makefile
include $(INCLUDES_DIR)/stack/hash/Makefile
include $(INCLUDES_DIR)/stack/resize/Makefile

